/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccessDates
 */
public class AccessDatesTest {
    private final AccessDates model = new AccessDates();

    /**
     * Model tests for AccessDates
     */
    @Test
    public void testAccessDates() {
        // TODO: test AccessDates
    }

    /**
     * Test the property 'endApproximate'
     */
    @Test
    public void endApproximateTest() {
        // TODO: test endApproximate
    }

    /**
     * Test the property 'endDateTime'
     */
    @Test
    public void endDateTimeTest() {
        // TODO: test endDateTime
    }

    /**
     * Test the property 'startApproximate'
     */
    @Test
    public void startApproximateTest() {
        // TODO: test startApproximate
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

}
