/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Attribution
 */
public class AttributionTest {
    private final Attribution model = new Attribution();

    /**
     * Model tests for Attribution
     */
    @Test
    public void testAttribution() {
        // TODO: test Attribution
    }

    /**
     * Test the property 'licenceName'
     */
    @Test
    public void licenceNameTest() {
        // TODO: test licenceName
    }

    /**
     * Test the property 'licenceUrl'
     */
    @Test
    public void licenceUrlTest() {
        // TODO: test licenceUrl
    }

    /**
     * Test the property 'sourceName'
     */
    @Test
    public void sourceNameTest() {
        // TODO: test sourceName
    }

    /**
     * Test the property 'sourceUrl'
     */
    @Test
    public void sourceUrlTest() {
        // TODO: test sourceUrl
    }

}
