/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Level;
import com.konfigthis.client.model.Segment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Classification
 */
public class ClassificationTest {
    private final Classification model = new Classification();

    /**
     * Model tests for Classification
     */
    @Test
    public void testClassification() {
        // TODO: test Classification
    }

    /**
     * Test the property 'genre'
     */
    @Test
    public void genreTest() {
        // TODO: test genre
    }

    /**
     * Test the property 'primary'
     */
    @Test
    public void primaryTest() {
        // TODO: test primary
    }

    /**
     * Test the property 'segment'
     */
    @Test
    public void segmentTest() {
        // TODO: test segment
    }

    /**
     * Test the property 'subGenre'
     */
    @Test
    public void subGenreTest() {
        // TODO: test subGenre
    }

    /**
     * Test the property 'subType'
     */
    @Test
    public void subTypeTest() {
        // TODO: test subType
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
