/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DateTimeFieldType;
import com.konfigthis.client.model.DurationField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DateTimeField
 */
public class DateTimeFieldTest {
    private final DateTimeField model = new DateTimeField();

    /**
     * Model tests for DateTimeField
     */
    @Test
    public void testDateTimeField() {
        // TODO: test DateTimeField
    }

    /**
     * Test the property 'durationField'
     */
    @Test
    public void durationFieldTest() {
        // TODO: test durationField
    }

    /**
     * Test the property 'leapDurationField'
     */
    @Test
    public void leapDurationFieldTest() {
        // TODO: test leapDurationField
    }

    /**
     * Test the property 'lenient'
     */
    @Test
    public void lenientTest() {
        // TODO: test lenient
    }

    /**
     * Test the property 'maximumValue'
     */
    @Test
    public void maximumValueTest() {
        // TODO: test maximumValue
    }

    /**
     * Test the property 'minimumValue'
     */
    @Test
    public void minimumValueTest() {
        // TODO: test minimumValue
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rangeDurationField'
     */
    @Test
    public void rangeDurationFieldTest() {
        // TODO: test rangeDurationField
    }

    /**
     * Test the property 'supported'
     */
    @Test
    public void supportedTest() {
        // TODO: test supported
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
