/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DisplaySettingExtension
 */
public class DisplaySettingExtensionTest {
    private final DisplaySettingExtension model = new DisplaySettingExtension();

    /**
     * Model tests for DisplaySettingExtension
     */
    @Test
    public void testDisplaySettingExtension() {
        // TODO: test DisplaySettingExtension
    }

    /**
     * Test the property 'softLanding'
     */
    @Test
    public void softLandingTest() {
        // TODO: test softLanding
    }

}
