/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DurationFieldType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DurationField
 */
public class DurationFieldTest {
    private final DurationField model = new DurationField();

    /**
     * Model tests for DurationField
     */
    @Test
    public void testDurationField() {
        // TODO: test DurationField
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'precise'
     */
    @Test
    public void preciseTest() {
        // TODO: test precise
    }

    /**
     * Test the property 'supported'
     */
    @Test
    public void supportedTest() {
        // TODO: test supported
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'unitMillis'
     */
    @Test
    public void unitMillisTest() {
        // TODO: test unitMillis
    }

}
