/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.joda.time.*;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EndDates
 */
public class EndDatesTest {
    private final EndDates model = new EndDates();

    /**
     * Model tests for EndDates
     */
    @Test
    public void testEndDates() {
        // TODO: test EndDates
    }

    /**
     * Test the property 'approximate'
     */
    @Test
    public void approximateTest() {
        // TODO: test approximate
    }

    /**
     * Test the property 'dateTime'
     */
    @Test
    public void dateTimeTest() {
        // TODO: test dateTime
    }

    /**
     * Test the property 'localDate'
     */
    @Test
    public void localDateTest() {
        // TODO: test localDate
    }

    /**
     * Test the property 'localTime'
     */
    @Test
    public void localTimeTest() {
        // TODO: test localTime
    }

    /**
     * Test the property 'noSpecificTime'
     */
    @Test
    public void noSpecificTimeTest() {
        // TODO: test noSpecificTime
    }

}
