/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EntityChanges
 */
public class EntityChangesTest {
    private final EntityChanges model = new EntityChanges();

    /**
     * Model tests for EntityChanges
     */
    @Test
    public void testEntityChanges() {
        // TODO: test EntityChanges
    }

    /**
     * Test the property 'changes'
     */
    @Test
    public void changesTest() {
        // TODO: test changes
    }

    /**
     * Test the property 'newlyCreated'
     */
    @Test
    public void newlyCreatedTest() {
        // TODO: test newlyCreated
    }

}
