/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Accessibility;
import com.konfigthis.client.model.Classification;
import com.konfigthis.client.model.EventDates;
import com.konfigthis.client.model.EventSalesDates;
import com.konfigthis.client.model.ExternalLink;
import com.konfigthis.client.model.Image;
import com.konfigthis.client.model.Location;
import com.konfigthis.client.model.Outlet;
import com.konfigthis.client.model.Place;
import com.konfigthis.client.model.PriceRange;
import com.konfigthis.client.model.Product;
import com.konfigthis.client.model.Promoter;
import com.konfigthis.client.model.SeatMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Event
 */
public class EventTest {
    private final Event model = new Event();

    /**
     * Model tests for Event
     */
    @Test
    public void testEvent() {
        // TODO: test Event
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'accessibility'
     */
    @Test
    public void accessibilityTest() {
        // TODO: test accessibility
    }

    /**
     * Test the property 'additionalInfo'
     */
    @Test
    public void additionalInfoTest() {
        // TODO: test additionalInfo
    }

    /**
     * Test the property 'classifications'
     */
    @Test
    public void classificationsTest() {
        // TODO: test classifications
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'externalLinks'
     */
    @Test
    public void externalLinksTest() {
        // TODO: test externalLinks
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'outlets'
     */
    @Test
    public void outletsTest() {
        // TODO: test outlets
    }

    /**
     * Test the property 'place'
     */
    @Test
    public void placeTest() {
        // TODO: test place
    }

    /**
     * Test the property 'pleaseNote'
     */
    @Test
    public void pleaseNoteTest() {
        // TODO: test pleaseNote
    }

    /**
     * Test the property 'priceRanges'
     */
    @Test
    public void priceRangesTest() {
        // TODO: test priceRanges
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

    /**
     * Test the property 'promoter'
     */
    @Test
    public void promoterTest() {
        // TODO: test promoter
    }

    /**
     * Test the property 'promoters'
     */
    @Test
    public void promotersTest() {
        // TODO: test promoters
    }

    /**
     * Test the property 'sales'
     */
    @Test
    public void salesTest() {
        // TODO: test sales
    }

    /**
     * Test the property 'seatmap'
     */
    @Test
    public void seatmapTest() {
        // TODO: test seatmap
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
