/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Geometry;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GeocodeExtension
 */
public class GeocodeExtensionTest {
    private final GeocodeExtension model = new GeocodeExtension();

    /**
     * Model tests for GeocodeExtension
     */
    @Test
    public void testGeocodeExtension() {
        // TODO: test GeocodeExtension
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'county'
     */
    @Test
    public void countyTest() {
        // TODO: test county
    }

    /**
     * Test the property 'formattedAddress'
     */
    @Test
    public void formattedAddressTest() {
        // TODO: test formattedAddress
    }

    /**
     * Test the property 'geometry'
     */
    @Test
    public void geometryTest() {
        // TODO: test geometry
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'route'
     */
    @Test
    public void routeTest() {
        // TODO: test route
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'streetNumber'
     */
    @Test
    public void streetNumberTest() {
        // TODO: test streetNumber
    }

}
