/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Chronology;
import com.konfigthis.client.model.DateTimeField;
import com.konfigthis.client.model.DateTimeFieldType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocalTime
 */
public class LocalTimeTest {
    private final LocalTime model = new LocalTime();

    /**
     * Model tests for LocalTime
     */
    @Test
    public void testLocalTime() {
        // TODO: test LocalTime
    }

    /**
     * Test the property 'chronology'
     */
    @Test
    public void chronologyTest() {
        // TODO: test chronology
    }

    /**
     * Test the property 'fieldTypes'
     */
    @Test
    public void fieldTypesTest() {
        // TODO: test fieldTypes
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'hourOfDay'
     */
    @Test
    public void hourOfDayTest() {
        // TODO: test hourOfDay
    }

    /**
     * Test the property 'millisOfDay'
     */
    @Test
    public void millisOfDayTest() {
        // TODO: test millisOfDay
    }

    /**
     * Test the property 'millisOfSecond'
     */
    @Test
    public void millisOfSecondTest() {
        // TODO: test millisOfSecond
    }

    /**
     * Test the property 'minuteOfHour'
     */
    @Test
    public void minuteOfHourTest() {
        // TODO: test minuteOfHour
    }

    /**
     * Test the property 'secondOfMinute'
     */
    @Test
    public void secondOfMinuteTest() {
        // TODO: test secondOfMinute
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
