/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.City;
import com.konfigthis.client.model.Country;
import com.konfigthis.client.model.Dma;
import com.konfigthis.client.model.ExternalLink;
import com.konfigthis.client.model.Image;
import com.konfigthis.client.model.Location;
import com.konfigthis.client.model.Market;
import com.konfigthis.client.model.Social;
import com.konfigthis.client.model.State;
import com.konfigthis.client.model.VenueBoxOfficeInfo;
import com.konfigthis.client.model.VenueGeneralInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Venue
 */
public class VenueTest {
    private final Venue model = new Venue();

    /**
     * Model tests for Venue
     */
    @Test
    public void testVenue() {
        // TODO: test Venue
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'accessibleSeatingDetail'
     */
    @Test
    public void accessibleSeatingDetailTest() {
        // TODO: test accessibleSeatingDetail
    }

    /**
     * Test the property 'additionalInfo'
     */
    @Test
    public void additionalInfoTest() {
        // TODO: test additionalInfo
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'boxOfficeInfo'
     */
    @Test
    public void boxOfficeInfoTest() {
        // TODO: test boxOfficeInfo
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'dma'
     */
    @Test
    public void dmaTest() {
        // TODO: test dma
    }

    /**
     * Test the property 'externalLinks'
     */
    @Test
    public void externalLinksTest() {
        // TODO: test externalLinks
    }

    /**
     * Test the property 'generalInfo'
     */
    @Test
    public void generalInfoTest() {
        // TODO: test generalInfo
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'markets'
     */
    @Test
    public void marketsTest() {
        // TODO: test markets
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'parkingDetail'
     */
    @Test
    public void parkingDetailTest() {
        // TODO: test parkingDetail
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'social'
     */
    @Test
    public void socialTest() {
        // TODO: test social
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'test'
     */
    @Test
    public void testTest() {
        // TODO: test test
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'upcomingEvents'
     */
    @Test
    public void upcomingEventsTest() {
        // TODO: test upcomingEvents
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
