/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VenueBoxOfficeInfo
 */
public class VenueBoxOfficeInfoTest {
    private final VenueBoxOfficeInfo model = new VenueBoxOfficeInfo();

    /**
     * Model tests for VenueBoxOfficeInfo
     */
    @Test
    public void testVenueBoxOfficeInfo() {
        // TODO: test VenueBoxOfficeInfo
    }

    /**
     * Test the property 'acceptedPaymentDetail'
     */
    @Test
    public void acceptedPaymentDetailTest() {
        // TODO: test acceptedPaymentDetail
    }

    /**
     * Test the property 'openHoursDetail'
     */
    @Test
    public void openHoursDetailTest() {
        // TODO: test openHoursDetail
    }

    /**
     * Test the property 'phoneNumberDetail'
     */
    @Test
    public void phoneNumberDetailTest() {
        // TODO: test phoneNumberDetail
    }

    /**
     * Test the property 'willCallDetail'
     */
    @Test
    public void willCallDetailTest() {
        // TODO: test willCallDetail
    }

}
