/*
 * Discovery API
 * The Ticketmaster Discovery API allows you to search for events, attractions, or venues.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Presale;
import com.konfigthis.client.model.PublicSaleDates;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Event&#39;s Sales Dates
 */
@ApiModel(description = "Event's Sales Dates")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EventSalesDates {
  public static final String SERIALIZED_NAME_PRESALES = "presales";
  @SerializedName(SERIALIZED_NAME_PRESALES)
  private List<Presale> presales = null;

  public static final String SERIALIZED_NAME_PUBLIC = "public";
  @SerializedName(SERIALIZED_NAME_PUBLIC)
  private PublicSaleDates _public;

  public EventSalesDates() {
  }

  public EventSalesDates presales(List<Presale> presales) {
    
    
    
    
    this.presales = presales;
    return this;
  }

  public EventSalesDates addPresalesItem(Presale presalesItem) {
    if (this.presales == null) {
      this.presales = new ArrayList<>();
    }
    this.presales.add(presalesItem);
    return this;
  }

   /**
   * Presale information on this event
   * @return presales
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Presale information on this event")

  public List<Presale> getPresales() {
    return presales;
  }


  public void setPresales(List<Presale> presales) {
    
    
    
    this.presales = presales;
  }


  public EventSalesDates _public(PublicSaleDates _public) {
    
    
    
    
    this._public = _public;
    return this;
  }

   /**
   * Get _public
   * @return _public
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PublicSaleDates getPublic() {
    return _public;
  }


  public void setPublic(PublicSaleDates _public) {
    
    
    
    this._public = _public;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EventSalesDates instance itself
   */
  public EventSalesDates putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventSalesDates eventSalesDates = (EventSalesDates) o;
    return Objects.equals(this.presales, eventSalesDates.presales) &&
        Objects.equals(this._public, eventSalesDates._public)&&
        Objects.equals(this.additionalProperties, eventSalesDates.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(presales, _public, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventSalesDates {\n");
    sb.append("    presales: ").append(toIndentedString(presales)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("presales");
    openapiFields.add("public");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EventSalesDates
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EventSalesDates.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventSalesDates is not found in the empty JSON string", EventSalesDates.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("presales") != null && !jsonObj.get("presales").isJsonNull()) {
        JsonArray jsonArraypresales = jsonObj.getAsJsonArray("presales");
        if (jsonArraypresales != null) {
          // ensure the json data is an array
          if (!jsonObj.get("presales").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `presales` to be an array in the JSON string but got `%s`", jsonObj.get("presales").toString()));
          }

          // validate the optional field `presales` (array)
          for (int i = 0; i < jsonArraypresales.size(); i++) {
            Presale.validateJsonObject(jsonArraypresales.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `public`
      if (jsonObj.get("public") != null && !jsonObj.get("public").isJsonNull()) {
        PublicSaleDates.validateJsonObject(jsonObj.getAsJsonObject("public"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventSalesDates.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventSalesDates' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventSalesDates> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventSalesDates.class));

       return (TypeAdapter<T>) new TypeAdapter<EventSalesDates>() {
           @Override
           public void write(JsonWriter out, EventSalesDates value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EventSalesDates read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EventSalesDates instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EventSalesDates given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EventSalesDates
  * @throws IOException if the JSON string is invalid with respect to EventSalesDates
  */
  public static EventSalesDates fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventSalesDates.class);
  }

 /**
  * Convert an instance of EventSalesDates to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

